const ROUTE = {
    HOME : "/",
    LOGIN : "/login",
    LEAD : "/lead",
    ACCOUNT : "/account",
    CONTACT : "/contact",
    CATEGORY : "/category_master",
    PRODUCT : "/product_master",
    OPPORTUNITY: "/opportunity",
    PROJECTMASTER: "/project_master",
    PROPOSAL : "/proposals",
    PROJECT : "/projects",
    INVOICE : "/invoices",
    PERMISSION : "/permissions",
    USER : "/users",
    TASK : "/tasks",
    COMMON_FIELD  : "/common-fields",
    CALENDAR : "/events",
    REPORT_DASHBOARD : "/reports",
    ACCOUNTDETAIL : "/account/:id",
    CONTACTDETAIL : "/contact/:id",
    EDITPROFILE : "/profile",
    CLIENTCONFIRMATION : "/client_confirmation",
    SETTING : "/settings",
    BACKUP : "/backup",
    EMAIL_TEMPLATE : "/email_template",
    LEDGERS : "/ledgers",
    STOCKITEM : "/stockItem",
    VOUCHER : "/vouchers",
    ORDER : "/orders",
    SETTING : "/setting",
}

export default ROUTE;